repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.8.2
    hooks:
      # Run the linter.
      - id: ruff
        types_or: [python, pyi]
        # TODO: should remove the ignore flag and fix errors !
        args: ["--fix", "--extend-ignore=F401,F841"]
      # Run the formatter.
      - id: ruff-format
        types_or: [python, pyi]
     # ðŸ”’ Silent Killers â€” audit Python for bad exception handling
  - repo: https://github.com/kilojoules/silent-killers
    rev: v0.1.7
    hooks:
      - id: silent-killers-audit
