repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.8.2
    hooks:
      # Run the linter.
      - id: ruff
        types_or: [python, pyi]
        args: ["--fix"]
        exclude: '^docusaurus-site/'
      # Run the formatter.
      - id: ruff-format
        types_or: [python, pyi]
        exclude: '^docusaurus-site/'
     # ðŸ”’ Silent Killers â€” audit Python for bad exception handling
  - repo: https://github.com/kilojoules/silent-killers
    rev: v0.1.7
    hooks:
      - id: silent-killers-audit
        exclude: '^docusaurus-site/'
        language_version: python3.11
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        files: '^docusaurus-site/.*\.(md|mdx|js|jsx)$'
        language_version: "20.11.1" # <-- Add this line
